eLearningProj/eLearningApp/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views
from . import consumers
urlpatterns = [
    path('home/', views.homepage, name='homepage'),
    path('signup/', views.user_signup, name='signup'),
    path('login/', views.user_login, name='login'),
    path('logout/', views.user_logout, name='logout'),
    path('profile/', views.profile, name='profile'),
    path('create_course/', views.create_course, name='create_course'),
    path('enroll/<int:course_id>', views.enroll, name='enroll'),
    path('view_course/<int:course_id>', views.view_course, name='view_course'),
    path('create_material/<int:course_id>', views.create_material, name='create_material'),
    path('delete_course/<int:course_id>', views.delete_course, name='delete_course'),
    path('delete_material/<int:mat_id>', views.delete_material, name='delete_material'),
    path('search/', views.search, name='search'),
    path('view_user/<int:user_id>', views.view_user, name='view_user'),
    path('remove_student/<int:course_id>/<int:student_id>', views.remove_student, name='remove_student'),
    path('leave_feedback/<int:course_id>', views.leave_feedback, name='leave_feedback'),
    path('home/inbox/', views.inbox, name='inbox'),
]

websocket_urlpatterns = [
    path('ws/chat/', consumers.ChatConsumer),
]

eLearningProj/eLearningProj/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('eLearning/', include('eLearningApp.urls')),
    path('api/', include('eLearningApp.api_urls')),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

eLearningProj/eLearningApp/models.py
from django.db import models
import os
from django.contrib.auth.models import AbstractUser
from django.core.validators import MaxValueValidator, MinValueValidator
# Create your models here.

class User(AbstractUser):
    first_name = models.CharField(max_length=100)
    last_name= models.CharField(max_length=100)
    isStudent = models.BooleanField(default=False)
    isTeacher = models.BooleanField(default=False)


class Course(models.Model):
    DIFFICULTY_LEVEL = (
    ('beginner', 'Beginner'),
    ('intermediate', 'Intermediate'),
    ('advanced', 'Advanced'),
    )
     
    name = models.CharField(max_length=100)
    teacher = models.ForeignKey(User, on_delete=models.CASCADE)
    description = models.TextField()
    level = models.CharField(max_length=20, choices=DIFFICULTY_LEVEL)

    def __str__(self):
        return self.name
    
class CourseMaterial(models.Model):
    course = models.ForeignKey(Course, on_delete=models.CASCADE)
    title = models.CharField(max_length=200)
    description = models.CharField(max_length=200)
    file =  models.FileField(blank=True, null=True)


class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    bio = models.TextField(max_length=500, blank=True)
    picture = models.ImageField(null=True, blank=True)

    def save(self, *args, **kwargs):
        # Delete the old picture if this profile already has one
        try:
            old_profile = Profile.objects.get(pk=self.pk)
            if old_profile.picture:
                if self.picture != old_profile.picture:
                    if os.path.isfile(old_profile.picture.path):
                        os.remove(old_profile.picture.path)
        except Profile.DoesNotExist:
            pass

        # Call the original save method
        super().save(*args, **kwargs)
            
class Enrollment(models.Model):
    student = models.ForeignKey(User, on_delete=models.CASCADE)
    course = models.ForeignKey(Course, on_delete=models.CASCADE)

class Feedback(models.Model):
    student = models.ForeignKey(User, on_delete=models.CASCADE)
    course = models.ForeignKey(Course, on_delete=models.CASCADE)
    rating = models.IntegerField(validators=[MinValueValidator(1), MaxValueValidator(5)]) 
    comments = models.TextField()
    timestamp = models.DateTimeField(auto_now_add=True)


class Notification(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    message = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"{self.user.username} - {self.message}"

eLearningProj/eLearningApp/forms.py
# accounts/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from .models import User, Profile, Course, CourseMaterial, Feedback

class SignUpForm(UserCreationForm):
    email = forms.EmailField()
    user_type=forms.ChoiceField(choices=[('teacher', 'Teacher'), ('student', 'Student')])

    class Meta:
        model = User
        fields = ['username','first_name','last_name','email', 'password1', 'password2','user_type']

    def save(self, commit=True):
        user = super().save(commit=False)
        user_type = self.cleaned_data.get('user_type')
        if user_type == 'teacher':
            user.isTeacher = True
            user.isStudent = False
        else:
            user.isTeacher = False
            user.isStudent = True
        if commit:
            user.save()
        return user


class ProfileForm(forms.ModelForm):
    class Meta:
        model = Profile
        fields = ['picture','bio']
        widgets = {
            'bio': forms.Textarea(attrs={'class': 'form-control', 'rows': 4}),
            'picture': forms.FileInput(attrs={'class': 'form-control-file'})
        }

class CourseForm(forms.ModelForm):
    level = forms.ChoiceField(choices=[('beginner', 'Beginner'),
                                    ('intermediate', 'Intermediate'),
                                    ('advanced', 'Advanced')])
    class Meta:
        model = Course
        fields = ['name','description','level']

class MaterialForm(forms.ModelForm):
    class Meta:
        model = CourseMaterial
        fields = ['title', 'description', 'file']


class SearchForm(forms.Form):
    query = forms.CharField(label='Search', max_length=100)

class FeedbackForm(forms.ModelForm):
    RATING_CHOICES = (
        (1, '1'),
        (2, '2'),
        (3, '3'),
        (4, '4'),
        (5, '5'),
    )

    rating = forms.ChoiceField(choices=RATING_CHOICES, label='Rating')
    class Meta:
        model = Feedback
        fields = ['rating', 'comments']

eLearningProj/eLearningApp/views.py
from django.contrib.auth import authenticate, login, logout
from rest_framework.decorators import api_view
from django.shortcuts import render, redirect, get_object_or_404
from .forms import SignUpForm, ProfileForm, CourseForm, MaterialForm, SearchForm, FeedbackForm
from .models import Profile, Course, Enrollment, CourseMaterial, User, Feedback, Notification
from .serializers import CourseSerializer, CourseMaterialSerializer
from django.core.exceptions import ObjectDoesNotExist
from .tasks import send_material_notification


# Homepage 
@api_view(['GET','POST'])
def homepage(request):
    # Checking user authentication
    if request.user.is_authenticated:
        # Splitting into teacher or student
        if request.user.isTeacher:
            # Render the 
            teacher_courses = Course.objects.filter(teacher=request.user)
            teacher_courses_serialized = CourseSerializer(teacher_courses, many=True).data
            return render(request, 'home.html', {'teacher_courses': teacher_courses_serialized})
        else:
            
            enrolled_course_ids = Enrollment.objects.filter(student=request.user).values_list('course_id', flat=True)
            enrolled_courses = Course.objects.filter(pk__in=enrolled_course_ids)
            enrolled_course_serialized = CourseSerializer(enrolled_courses, many=True).data

            available_courses = Course.objects.exclude(id__in=enrolled_courses)
            student_courses_serialized = CourseSerializer(available_courses, many=True).data
            
            return render(request, 'home.html', {'student_courses': student_courses_serialized, 'enrolled_courses': enrolled_course_serialized})
    else:
        return render(request, 'home.html')


def user_signup(request):
    if request.method == 'POST':
        form = SignUpForm(request.POST)
        if form.is_valid():
            form.save()
            username = form.cleaned_data.get('username')
            raw_password = form.cleaned_data.get('password1')
            user = authenticate(username=username, password=raw_password)
            if user is not None:
                login(request, user)
                return redirect('../home')
        else:

            return redirect ('registration/signup.html', {'form': form})
    else:
        form = SignUpForm()
    return render(request, 'registration/signup.html', {'form': form})

def user_login(request):
    if request.method == 'POST':
        username = request.POST['username']
        password = request.POST['password']
        user = authenticate(request, username=username, password=password)
        if user is not None:
            login(request, user)
            return redirect('../home')  # Redirect to home page after successful login
    return render(request, 'registration/login.html')

def user_logout(request):
    logout(request)
    return redirect('../home')


def profile(request):
    profile = Profile.objects.filter(user=request.user).first()
    if request.method == 'POST':
        form = ProfileForm(request.POST, instance=profile)
        if form.is_valid():
            profile = form.save(commit=False)
            profile.user = request.user
            if 'picture' in request.FILES:
                profile.picture = request.FILES['picture']
            profile.save()
            return redirect('homepage')
    else:
        form = ProfileForm(instance=profile)
    return render(request, 'profile.html', {'form': form})

def create_course(request):
    if request.method == 'POST':
        form = CourseForm(request.POST)
        if form.is_valid():
            course = form.save(commit=False)
            course.teacher = request.user  # Set the current user as the teacher
            course.save()
            return redirect('homepage')  # Redirect to home page or course detail page
    else:
        form = CourseForm()
    return render(request, 'course/create_course.html', {'form': form})

def delete_course(request, course_id):
    if request.method == 'POST':
        # Retrieve the course object from the database
        course = get_object_or_404(Course, pk=course_id)
        # Delete the course
        course.delete()
    # Redirect to a relevant page after course removal
    return redirect('homepage')  

def enroll(request, course_id):
    if request.method == 'POST':
        # Get the current user
        user = request.user
        # Get the course object or return 404 if not found
        course = get_object_or_404(Course, pk=course_id)
        # Create an enrollment instance
        enrollment = Enrollment.objects.create(student=user, course=course)
                # Retrieve the teacher of the course
        teacher = enrollment.course.teacher
        course_name = course.name
        # Create notification for the teacher
        message = f"New student enrolled in your course '{course_name}':{enrollment.student.username}"
        Notification.objects.create(user=teacher, message=message)

        return redirect('homepage')  # Redirect to home page or course detail page
    

def view_course(request,course_id):
    materials = CourseMaterial.objects.filter(course_id=course_id)
    serializer = CourseMaterialSerializer(materials, many=True)
    enrolled = Enrollment.objects.filter(course_id=course_id)
    form = FeedbackForm()
    feedbacks = Feedback.objects.filter(course_id=course_id)
    if materials.exists():
        return render(request, 'course/view_course.html', {'enroll':enrolled,
                                                           'materials': serializer.data, 
                                                           'course_id': course_id,
                                                           'feedbacks': feedbacks,
                                                           'form':form})
    else:
        return render(request, 'course/view_course.html', {'enroll':enrolled,
                                                           'materials': None, 
                                                           'course_id' : course_id,
                                                           'feedbacks': feedbacks, 
                                                           'form':form})

            
def create_material(request, course_id):
    if request.method == 'POST':
        form = MaterialForm(request.POST, request.FILES, initial={'course': course_id})
        if form.is_valid():
            material = form.save(commit=False)
            material.course_id = course_id
            material.save()
            send_material_notification.delay(course_id)
            return redirect('view_course', course_id=course_id)
        
    return redirect('view_course', course_id=course_id)  # Redirect even if the form is not valid

def delete_material(request, mat_id):
    material = get_object_or_404(CourseMaterial, pk=mat_id)
    material.delete()
    return redirect('view_course', course_id=material.course_id)


def search(request):
    if request.method == 'GET':
        form = SearchForm(request.GET)
        if form.is_valid():
            query = form.cleaned_data.get('query')
            # Perform the search query
            results = User.objects.filter(username__icontains=query).exclude(pk=request.user.pk)
            return render(request, 'search_results.html', {'results': results})

def view_user(request, user_id):
    user = User.objects.get(pk=user_id)
    try:
        user = User.objects.get(pk=user_id)
        profile = Profile.objects.get(user_id=user_id)
    except ObjectDoesNotExist:
        profile = None
    # Retrieve enrolled courses if the user is a student
    enrolled_courses = None
    if user.isStudent:
        enrolled_courses = Course.objects.filter(enrollment__student=user)
    # Retrieve produced courses if the user is a teacher
    produced_courses = None
    if user.isTeacher:
        produced_courses = Course.objects.filter(teacher=user)
    return render(request, 'user_profile.html', {'user': user, 
                                                 'profile':profile,
                                                 'enrolled_courses': enrolled_courses,
                                                 'produced_courses': produced_courses})

def remove_student(request,course_id,student_id):
    enrollment = get_object_or_404(Enrollment, course_id=course_id, student_id=student_id)
    enrollment.delete()
    return redirect('view_course', course_id=course_id)

def leave_feedback(request, course_id):
    if request.method == 'POST':
        form = FeedbackForm(request.POST)
        if form.is_valid():
            feedback = form.save(commit=False)
            feedback.student = request.user
            feedback.course_id = course_id
            feedback.save()
            return redirect('view_course', course_id=course_id)
    # Return a redirect in case of invalid form data or non-POST request
    return redirect('view_course',course_id=course_id)

def inbox(request):
    if request.user.is_authenticated:
        if request.user.isTeacher:
            notifications = Notification.objects.filter(user=request.user).order_by('-created_at')
        elif request.user.isStudent:
            notifications = Notification.objects.filter(user=request.user).order_by('-created_at')
        return render(request, 'inbox.html', {'notifications': notifications})
    return render(request, 'inbox.html', {'notifications': None})

eLearningProj/eLearningApp/templates/course/create_course.html
<!-- profile.html -->
{% extends "base.html" %}
{% block title %}Create Course{% endblock %}
{% block content %}
<a href="../home" class="btn btn-secondary" style="margin: 3px;">Back</a>
<h2>Create Course</h2>

<form method="post" class="my-4">
    {% csrf_token %}
    <div class="form-group">
        {{ form.as_p }}
    </div>
    <button type="submit" class="btn btn-primary">Create</button>
</form>

{% endblock %}

eLearningProj/eLearningApp/templates/course/view_course.html
<!-- profile.html -->
{% extends "base.html" %}
{% block title %}{% endblock %}
{% block content %}
<a href="../home" class="btn btn-secondary" style="margin: 3px;">Back</a>


{% if user.isTeacher %}
    <h2>Uploaded Materials</h2>
    <ul class="list-group mb-3">
        {% for material in materials %}
            <li class="list-group-item d-flex justify-content-between align-items-center">
                <a href="{{ material.file }}">{{ material.title }}</a>
                <form method="POST" action="{% url 'delete_material' material.id %}">
                    {% csrf_token %}
                    <button type="submit" class="btn btn-danger">Remove</button>
                </form>
            </li>
        {% empty %}
            <li class="list-group-item">No materials uploaded</li>
        {% endfor %}
    </ul>
    
    <h2>Students Enrolled</h2>
    <ul class="list-group mb-3">
        {% for enr in enroll %}
            <li class="list-group-item">
                <div class="d-flex justify-content-between align-items-center">
                    <span>{{ enr.student }}</span>
                    <span>{{ enr.student.email }}</span>
                </div>
                <form method="POST" action="{% url 'remove_student' enr.course.id enr.student.id %}">
                    {% csrf_token %}
                    <button type="submit" class="btn btn-danger">Remove</button>
                </form>
            </li>
        {% empty %}
            <li class="list-group-item">No students enrolled</li>
        {% endfor %}
    </ul>

    <h2>Upload Material</h2>
    <form method="POST" action="{% url 'create_material' course_id %}" enctype="multipart/form-data">
        {% csrf_token %}
        <div class="mb-3">
            <label for="id_title" class="form-label">Title:</label>
            <input type="text" class="form-control" id="id_title" name="title">
        </div>
        <div class="mb-3">
            <label for="id_description" class="form-label">Description:</label>
            <input type="text" class="form-control" id="id_description" name="description">
        </div>
        <div class="mb-3">
            <label for="id_file" class="form-label">File:</label>
            <input type="file" class="form-control" id="id_file" name="file">
        </div>
        <button type="submit" class="btn btn-primary">Upload</button>
    </form>

    <h2>Feedbacks</h2>
    {% for feedback in feedbacks %}
        <div class="card mb-3">
            <div class="card-body">
                <h5 class="card-title">Rating: {{ feedback.rating }}</h5>
                <p class="card-text">Comments: {{ feedback.comments }}</p>
            </div>
        </div>
    {% empty %}
        <p>No feedbacks available</p>
    {% endfor %}
{% endif %}

{% if user.isStudent %}
    <h2>Available Materials</h2>
    <ul class="list-group mb-3">
        {% for mat in materials %}
            <li class="list-group-item">
                <a href="{{ mat.file }}">{{ mat.title }}</a>
                <p>{{ mat.description }}</p>
            </li>
        {% empty %}
            <li class="list-group-item">No materials available</li>
        {% endfor %}
    </ul>

    <h2>Leave Feedback</h2>
    <form method="post" action="{% url 'leave_feedback' course_id %}">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit" class="btn btn-primary">Submit Feedback</button>
    </form>
{% endif %}
{% endblock %}